//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPAClientApp.UsuariosService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EUsuario", Namespace="http://schemas.datacontract.org/2004/07/Services.Model")]
    [System.SerializableAttribute()]
    public partial class EUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BajaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoPostalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> SalarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Baja {
            get {
                return this.BajaField;
            }
            set {
                if ((this.BajaField.Equals(value) != true)) {
                    this.BajaField = value;
                    this.RaisePropertyChanged("Baja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ciudad {
            get {
                return this.CiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadField, value) != true)) {
                    this.CiudadField = value;
                    this.RaisePropertyChanged("Ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Clave {
            get {
                return this.ClaveField;
            }
            set {
                if ((this.ClaveField.Equals(value) != true)) {
                    this.ClaveField = value;
                    this.RaisePropertyChanged("Clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoPostal {
            get {
                return this.CodigoPostalField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoPostalField, value) != true)) {
                    this.CodigoPostalField = value;
                    this.RaisePropertyChanged("CodigoPostal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Registro {
            get {
                return this.RegistroField;
            }
            set {
                if ((this.RegistroField.Equals(value) != true)) {
                    this.RegistroField = value;
                    this.RaisePropertyChanged("Registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Salario {
            get {
                return this.SalarioField;
            }
            set {
                if ((this.SalarioField.Equals(value) != true)) {
                    this.SalarioField = value;
                    this.RaisePropertyChanged("Salario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoUsuario {
            get {
                return this.TipoUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoUsuarioField, value) != true)) {
                    this.TipoUsuarioField = value;
                    this.RaisePropertyChanged("TipoUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnswerMessage", Namespace="http://schemas.datacontract.org/2004/07/Services.Model")]
    [System.SerializableAttribute()]
    public partial class AnswerMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Key {
            get {
                return this.KeyField;
            }
            set {
                if ((this.KeyField.Equals(value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UsuariosService.IUsuariosService")]
    public interface IUsuariosService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/GetUsuarios", ReplyAction="http://tempuri.org/IUsuariosService/GetUsuariosResponse")]
        SPAClientApp.UsuariosService.EUsuario[] GetUsuarios(string status, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/GetUsuarios", ReplyAction="http://tempuri.org/IUsuariosService/GetUsuariosResponse")]
        System.Threading.Tasks.Task<SPAClientApp.UsuariosService.EUsuario[]> GetUsuariosAsync(string status, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/AddUsuario", ReplyAction="http://tempuri.org/IUsuariosService/AddUsuarioResponse")]
        SPAClientApp.UsuariosService.AnswerMessage AddUsuario(SPAClientApp.UsuariosService.EUsuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/AddUsuario", ReplyAction="http://tempuri.org/IUsuariosService/AddUsuarioResponse")]
        System.Threading.Tasks.Task<SPAClientApp.UsuariosService.AnswerMessage> AddUsuarioAsync(SPAClientApp.UsuariosService.EUsuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/UpdateUsuario", ReplyAction="http://tempuri.org/IUsuariosService/UpdateUsuarioResponse")]
        SPAClientApp.UsuariosService.AnswerMessage UpdateUsuario(SPAClientApp.UsuariosService.EUsuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/UpdateUsuario", ReplyAction="http://tempuri.org/IUsuariosService/UpdateUsuarioResponse")]
        System.Threading.Tasks.Task<SPAClientApp.UsuariosService.AnswerMessage> UpdateUsuarioAsync(SPAClientApp.UsuariosService.EUsuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/GetUsuarioByEmail", ReplyAction="http://tempuri.org/IUsuariosService/GetUsuarioByEmailResponse")]
        SPAClientApp.UsuariosService.EUsuario GetUsuarioByEmail(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/GetUsuarioByEmail", ReplyAction="http://tempuri.org/IUsuariosService/GetUsuarioByEmailResponse")]
        System.Threading.Tasks.Task<SPAClientApp.UsuariosService.EUsuario> GetUsuarioByEmailAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/ChangeStatusUsuario", ReplyAction="http://tempuri.org/IUsuariosService/ChangeStatusUsuarioResponse")]
        SPAClientApp.UsuariosService.AnswerMessage ChangeStatusUsuario(int usaurioID, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/ChangeStatusUsuario", ReplyAction="http://tempuri.org/IUsuariosService/ChangeStatusUsuarioResponse")]
        System.Threading.Tasks.Task<SPAClientApp.UsuariosService.AnswerMessage> ChangeStatusUsuarioAsync(int usaurioID, string status);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuariosServiceChannel : SPAClientApp.UsuariosService.IUsuariosService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuariosServiceClient : System.ServiceModel.ClientBase<SPAClientApp.UsuariosService.IUsuariosService>, SPAClientApp.UsuariosService.IUsuariosService {
        
        public UsuariosServiceClient() {
        }
        
        public UsuariosServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuariosServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuariosServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuariosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SPAClientApp.UsuariosService.EUsuario[] GetUsuarios(string status, string nombre) {
            return base.Channel.GetUsuarios(status, nombre);
        }
        
        public System.Threading.Tasks.Task<SPAClientApp.UsuariosService.EUsuario[]> GetUsuariosAsync(string status, string nombre) {
            return base.Channel.GetUsuariosAsync(status, nombre);
        }
        
        public SPAClientApp.UsuariosService.AnswerMessage AddUsuario(SPAClientApp.UsuariosService.EUsuario usuario) {
            return base.Channel.AddUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<SPAClientApp.UsuariosService.AnswerMessage> AddUsuarioAsync(SPAClientApp.UsuariosService.EUsuario usuario) {
            return base.Channel.AddUsuarioAsync(usuario);
        }
        
        public SPAClientApp.UsuariosService.AnswerMessage UpdateUsuario(SPAClientApp.UsuariosService.EUsuario usuario) {
            return base.Channel.UpdateUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<SPAClientApp.UsuariosService.AnswerMessage> UpdateUsuarioAsync(SPAClientApp.UsuariosService.EUsuario usuario) {
            return base.Channel.UpdateUsuarioAsync(usuario);
        }
        
        public SPAClientApp.UsuariosService.EUsuario GetUsuarioByEmail(string email, string password) {
            return base.Channel.GetUsuarioByEmail(email, password);
        }
        
        public System.Threading.Tasks.Task<SPAClientApp.UsuariosService.EUsuario> GetUsuarioByEmailAsync(string email, string password) {
            return base.Channel.GetUsuarioByEmailAsync(email, password);
        }
        
        public SPAClientApp.UsuariosService.AnswerMessage ChangeStatusUsuario(int usaurioID, string status) {
            return base.Channel.ChangeStatusUsuario(usaurioID, status);
        }
        
        public System.Threading.Tasks.Task<SPAClientApp.UsuariosService.AnswerMessage> ChangeStatusUsuarioAsync(int usaurioID, string status) {
            return base.Channel.ChangeStatusUsuarioAsync(usaurioID, status);
        }
    }
}
