//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPAClientApp.PedidosProveedoresService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EPedidoProveedor", Namespace="http://schemas.datacontract.org/2004/07/Services.Model")]
    [System.SerializableAttribute()]
    public partial class EPedidoProveedor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClaveProveedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SPAClientApp.PedidosProveedoresService.EInsumoPedido[] InsumosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoPedidoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClaveProveedor {
            get {
                return this.ClaveProveedorField;
            }
            set {
                if ((this.ClaveProveedorField.Equals(value) != true)) {
                    this.ClaveProveedorField = value;
                    this.RaisePropertyChanged("ClaveProveedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SPAClientApp.PedidosProveedoresService.EInsumoPedido[] Insumos {
            get {
                return this.InsumosField;
            }
            set {
                if ((object.ReferenceEquals(this.InsumosField, value) != true)) {
                    this.InsumosField = value;
                    this.RaisePropertyChanged("Insumos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoPedido {
            get {
                return this.TipoPedidoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoPedidoField, value) != true)) {
                    this.TipoPedidoField = value;
                    this.RaisePropertyChanged("TipoPedido");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EInsumoPedido", Namespace="http://schemas.datacontract.org/2004/07/Services.Model")]
    [System.SerializableAttribute()]
    public partial class EInsumoPedido : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoInsumoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoPedidoProveedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoInsumo {
            get {
                return this.CodigoInsumoField;
            }
            set {
                if ((this.CodigoInsumoField.Equals(value) != true)) {
                    this.CodigoInsumoField = value;
                    this.RaisePropertyChanged("CodigoInsumo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoPedidoProveedor {
            get {
                return this.CodigoPedidoProveedorField;
            }
            set {
                if ((this.CodigoPedidoProveedorField.Equals(value) != true)) {
                    this.CodigoPedidoProveedorField = value;
                    this.RaisePropertyChanged("CodigoPedidoProveedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnswerMessage", Namespace="http://schemas.datacontract.org/2004/07/Services.Model")]
    [System.SerializableAttribute()]
    public partial class AnswerMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Key {
            get {
                return this.KeyField;
            }
            set {
                if ((this.KeyField.Equals(value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PedidosProveedoresService.IPedidosProveedoresService")]
    public interface IPedidosProveedoresService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidosProveedoresService/AddPedidoProveedor", ReplyAction="http://tempuri.org/IPedidosProveedoresService/AddPedidoProveedorResponse")]
        SPAClientApp.PedidosProveedoresService.AnswerMessage AddPedidoProveedor(SPAClientApp.PedidosProveedoresService.EPedidoProveedor pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidosProveedoresService/AddPedidoProveedor", ReplyAction="http://tempuri.org/IPedidosProveedoresService/AddPedidoProveedorResponse")]
        System.Threading.Tasks.Task<SPAClientApp.PedidosProveedoresService.AnswerMessage> AddPedidoProveedorAsync(SPAClientApp.PedidosProveedoresService.EPedidoProveedor pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidosProveedoresService/ChangeStatusPeidoProveedor", ReplyAction="http://tempuri.org/IPedidosProveedoresService/ChangeStatusPeidoProveedorResponse")]
        SPAClientApp.PedidosProveedoresService.AnswerMessage ChangeStatusPeidoProveedor(int idPedido, string Status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidosProveedoresService/ChangeStatusPeidoProveedor", ReplyAction="http://tempuri.org/IPedidosProveedoresService/ChangeStatusPeidoProveedorResponse")]
        System.Threading.Tasks.Task<SPAClientApp.PedidosProveedoresService.AnswerMessage> ChangeStatusPeidoProveedorAsync(int idPedido, string Status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidosProveedoresService/GetPedidosProveedores", ReplyAction="http://tempuri.org/IPedidosProveedoresService/GetPedidosProveedoresResponse")]
        SPAClientApp.PedidosProveedoresService.EPedidoProveedor[] GetPedidosProveedores(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidosProveedoresService/GetPedidosProveedores", ReplyAction="http://tempuri.org/IPedidosProveedoresService/GetPedidosProveedoresResponse")]
        System.Threading.Tasks.Task<SPAClientApp.PedidosProveedoresService.EPedidoProveedor[]> GetPedidosProveedoresAsync(System.Nullable<int> id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPedidosProveedoresServiceChannel : SPAClientApp.PedidosProveedoresService.IPedidosProveedoresService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PedidosProveedoresServiceClient : System.ServiceModel.ClientBase<SPAClientApp.PedidosProveedoresService.IPedidosProveedoresService>, SPAClientApp.PedidosProveedoresService.IPedidosProveedoresService {
        
        public PedidosProveedoresServiceClient() {
        }
        
        public PedidosProveedoresServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PedidosProveedoresServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidosProveedoresServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidosProveedoresServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SPAClientApp.PedidosProveedoresService.AnswerMessage AddPedidoProveedor(SPAClientApp.PedidosProveedoresService.EPedidoProveedor pedido) {
            return base.Channel.AddPedidoProveedor(pedido);
        }
        
        public System.Threading.Tasks.Task<SPAClientApp.PedidosProveedoresService.AnswerMessage> AddPedidoProveedorAsync(SPAClientApp.PedidosProveedoresService.EPedidoProveedor pedido) {
            return base.Channel.AddPedidoProveedorAsync(pedido);
        }
        
        public SPAClientApp.PedidosProveedoresService.AnswerMessage ChangeStatusPeidoProveedor(int idPedido, string Status) {
            return base.Channel.ChangeStatusPeidoProveedor(idPedido, Status);
        }
        
        public System.Threading.Tasks.Task<SPAClientApp.PedidosProveedoresService.AnswerMessage> ChangeStatusPeidoProveedorAsync(int idPedido, string Status) {
            return base.Channel.ChangeStatusPeidoProveedorAsync(idPedido, Status);
        }
        
        public SPAClientApp.PedidosProveedoresService.EPedidoProveedor[] GetPedidosProveedores(System.Nullable<int> id) {
            return base.Channel.GetPedidosProveedores(id);
        }
        
        public System.Threading.Tasks.Task<SPAClientApp.PedidosProveedoresService.EPedidoProveedor[]> GetPedidosProveedoresAsync(System.Nullable<int> id) {
            return base.Channel.GetPedidosProveedoresAsync(id);
        }
    }
}
