//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPAClientApp.ProductosService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EProducto", Namespace="http://schemas.datacontract.org/2004/07/Services.Model")]
    [System.SerializableAttribute()]
    public partial class EProducto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoRecetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecioCompraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecioVentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RestriccionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoReceta {
            get {
                return this.CodigoRecetaField;
            }
            set {
                if ((this.CodigoRecetaField.Equals(value) != true)) {
                    this.CodigoRecetaField = value;
                    this.RaisePropertyChanged("CodigoReceta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PrecioCompra {
            get {
                return this.PrecioCompraField;
            }
            set {
                if ((this.PrecioCompraField.Equals(value) != true)) {
                    this.PrecioCompraField = value;
                    this.RaisePropertyChanged("PrecioCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PrecioVenta {
            get {
                return this.PrecioVentaField;
            }
            set {
                if ((this.PrecioVentaField.Equals(value) != true)) {
                    this.PrecioVentaField = value;
                    this.RaisePropertyChanged("PrecioVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Registro {
            get {
                return this.RegistroField;
            }
            set {
                if ((this.RegistroField.Equals(value) != true)) {
                    this.RegistroField = value;
                    this.RaisePropertyChanged("Registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Restricciones {
            get {
                return this.RestriccionesField;
            }
            set {
                if ((object.ReferenceEquals(this.RestriccionesField, value) != true)) {
                    this.RestriccionesField = value;
                    this.RaisePropertyChanged("Restricciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EReceta", Namespace="http://schemas.datacontract.org/2004/07/Services.Model")]
    [System.SerializableAttribute()]
    public partial class EReceta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SPAClientApp.ProductosService.EIngrediente[] IngredientesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Clave {
            get {
                return this.ClaveField;
            }
            set {
                if ((this.ClaveField.Equals(value) != true)) {
                    this.ClaveField = value;
                    this.RaisePropertyChanged("Clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SPAClientApp.ProductosService.EIngrediente[] Ingredientes {
            get {
                return this.IngredientesField;
            }
            set {
                if ((object.ReferenceEquals(this.IngredientesField, value) != true)) {
                    this.IngredientesField = value;
                    this.RaisePropertyChanged("Ingredientes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EIngrediente", Namespace="http://schemas.datacontract.org/2004/07/Services.Model")]
    [System.SerializableAttribute()]
    public partial class EIngrediente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CantidadIngredienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CantidadInsumoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoInsumoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreInsumoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecioInsumoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double CantidadIngrediente {
            get {
                return this.CantidadIngredienteField;
            }
            set {
                if ((this.CantidadIngredienteField.Equals(value) != true)) {
                    this.CantidadIngredienteField = value;
                    this.RaisePropertyChanged("CantidadIngrediente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double CantidadInsumo {
            get {
                return this.CantidadInsumoField;
            }
            set {
                if ((this.CantidadInsumoField.Equals(value) != true)) {
                    this.CantidadInsumoField = value;
                    this.RaisePropertyChanged("CantidadInsumo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoInsumo {
            get {
                return this.CodigoInsumoField;
            }
            set {
                if ((this.CodigoInsumoField.Equals(value) != true)) {
                    this.CodigoInsumoField = value;
                    this.RaisePropertyChanged("CodigoInsumo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreInsumo {
            get {
                return this.NombreInsumoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreInsumoField, value) != true)) {
                    this.NombreInsumoField = value;
                    this.RaisePropertyChanged("NombreInsumo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PrecioInsumo {
            get {
                return this.PrecioInsumoField;
            }
            set {
                if ((this.PrecioInsumoField.Equals(value) != true)) {
                    this.PrecioInsumoField = value;
                    this.RaisePropertyChanged("PrecioInsumo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unidad {
            get {
                return this.UnidadField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadField, value) != true)) {
                    this.UnidadField = value;
                    this.RaisePropertyChanged("Unidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EInsumo", Namespace="http://schemas.datacontract.org/2004/07/Services.Model")]
    [System.SerializableAttribute()]
    public partial class EInsumo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecioCompraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProveedorDeInsumoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RestriccionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnidadMedidaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PrecioCompra {
            get {
                return this.PrecioCompraField;
            }
            set {
                if ((this.PrecioCompraField.Equals(value) != true)) {
                    this.PrecioCompraField = value;
                    this.RaisePropertyChanged("PrecioCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProveedorDeInsumo {
            get {
                return this.ProveedorDeInsumoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProveedorDeInsumoField, value) != true)) {
                    this.ProveedorDeInsumoField = value;
                    this.RaisePropertyChanged("ProveedorDeInsumo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Registro {
            get {
                return this.RegistroField;
            }
            set {
                if ((this.RegistroField.Equals(value) != true)) {
                    this.RegistroField = value;
                    this.RaisePropertyChanged("Registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Restricciones {
            get {
                return this.RestriccionesField;
            }
            set {
                if ((object.ReferenceEquals(this.RestriccionesField, value) != true)) {
                    this.RestriccionesField = value;
                    this.RaisePropertyChanged("Restricciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnidadMedida {
            get {
                return this.UnidadMedidaField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadMedidaField, value) != true)) {
                    this.UnidadMedidaField = value;
                    this.RaisePropertyChanged("UnidadMedida");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnswerMessage", Namespace="http://schemas.datacontract.org/2004/07/Services.Model")]
    [System.SerializableAttribute()]
    public partial class AnswerMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Key {
            get {
                return this.KeyField;
            }
            set {
                if ((this.KeyField.Equals(value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductosService.IProductosService")]
    public interface IProductosService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductosService/GetProductosList", ReplyAction="http://tempuri.org/IProductosService/GetProductosListResponse")]
        SPAClientApp.ProductosService.EProducto[] GetProductosList(string criterio, string valor, System.DateTime fecha, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductosService/GetProductosList", ReplyAction="http://tempuri.org/IProductosService/GetProductosListResponse")]
        System.Threading.Tasks.Task<SPAClientApp.ProductosService.EProducto[]> GetProductosListAsync(string criterio, string valor, System.DateTime fecha, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductosService/GetReceta", ReplyAction="http://tempuri.org/IProductosService/GetRecetaResponse")]
        SPAClientApp.ProductosService.EReceta GetReceta(int clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductosService/GetReceta", ReplyAction="http://tempuri.org/IProductosService/GetRecetaResponse")]
        System.Threading.Tasks.Task<SPAClientApp.ProductosService.EReceta> GetRecetaAsync(int clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductosService/GetIngredientes", ReplyAction="http://tempuri.org/IProductosService/GetIngredientesResponse")]
        SPAClientApp.ProductosService.EInsumo[] GetIngredientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductosService/GetIngredientes", ReplyAction="http://tempuri.org/IProductosService/GetIngredientesResponse")]
        System.Threading.Tasks.Task<SPAClientApp.ProductosService.EInsumo[]> GetIngredientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductosService/AddProducto", ReplyAction="http://tempuri.org/IProductosService/AddProductoResponse")]
        SPAClientApp.ProductosService.AnswerMessage AddProducto(SPAClientApp.ProductosService.EProducto producto, SPAClientApp.ProductosService.EReceta receta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductosService/AddProducto", ReplyAction="http://tempuri.org/IProductosService/AddProductoResponse")]
        System.Threading.Tasks.Task<SPAClientApp.ProductosService.AnswerMessage> AddProductoAsync(SPAClientApp.ProductosService.EProducto producto, SPAClientApp.ProductosService.EReceta receta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductosService/IsDuplicated", ReplyAction="http://tempuri.org/IProductosService/IsDuplicatedResponse")]
        bool IsDuplicated(string nombreActual, string nombreABuscar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductosService/IsDuplicated", ReplyAction="http://tempuri.org/IProductosService/IsDuplicatedResponse")]
        System.Threading.Tasks.Task<bool> IsDuplicatedAsync(string nombreActual, string nombreABuscar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductosService/UpdateProducto", ReplyAction="http://tempuri.org/IProductosService/UpdateProductoResponse")]
        SPAClientApp.ProductosService.AnswerMessage UpdateProducto(SPAClientApp.ProductosService.EProducto producto, SPAClientApp.ProductosService.EReceta receta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductosService/UpdateProducto", ReplyAction="http://tempuri.org/IProductosService/UpdateProductoResponse")]
        System.Threading.Tasks.Task<SPAClientApp.ProductosService.AnswerMessage> UpdateProductoAsync(SPAClientApp.ProductosService.EProducto producto, SPAClientApp.ProductosService.EReceta receta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductosService/ChangeProductoStatus", ReplyAction="http://tempuri.org/IProductosService/ChangeProductoStatusResponse")]
        SPAClientApp.ProductosService.AnswerMessage ChangeProductoStatus(int productoID, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductosService/ChangeProductoStatus", ReplyAction="http://tempuri.org/IProductosService/ChangeProductoStatusResponse")]
        System.Threading.Tasks.Task<SPAClientApp.ProductosService.AnswerMessage> ChangeProductoStatusAsync(int productoID, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductosService/CheckIngredientesStatus", ReplyAction="http://tempuri.org/IProductosService/CheckIngredientesStatusResponse")]
        string CheckIngredientesStatus(SPAClientApp.ProductosService.EIngrediente[] ingredientes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductosService/CheckIngredientesStatus", ReplyAction="http://tempuri.org/IProductosService/CheckIngredientesStatusResponse")]
        System.Threading.Tasks.Task<string> CheckIngredientesStatusAsync(SPAClientApp.ProductosService.EIngrediente[] ingredientes);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductosServiceChannel : SPAClientApp.ProductosService.IProductosService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductosServiceClient : System.ServiceModel.ClientBase<SPAClientApp.ProductosService.IProductosService>, SPAClientApp.ProductosService.IProductosService {
        
        public ProductosServiceClient() {
        }
        
        public ProductosServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductosServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductosServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SPAClientApp.ProductosService.EProducto[] GetProductosList(string criterio, string valor, System.DateTime fecha, string status) {
            return base.Channel.GetProductosList(criterio, valor, fecha, status);
        }
        
        public System.Threading.Tasks.Task<SPAClientApp.ProductosService.EProducto[]> GetProductosListAsync(string criterio, string valor, System.DateTime fecha, string status) {
            return base.Channel.GetProductosListAsync(criterio, valor, fecha, status);
        }
        
        public SPAClientApp.ProductosService.EReceta GetReceta(int clave) {
            return base.Channel.GetReceta(clave);
        }
        
        public System.Threading.Tasks.Task<SPAClientApp.ProductosService.EReceta> GetRecetaAsync(int clave) {
            return base.Channel.GetRecetaAsync(clave);
        }
        
        public SPAClientApp.ProductosService.EInsumo[] GetIngredientes() {
            return base.Channel.GetIngredientes();
        }
        
        public System.Threading.Tasks.Task<SPAClientApp.ProductosService.EInsumo[]> GetIngredientesAsync() {
            return base.Channel.GetIngredientesAsync();
        }
        
        public SPAClientApp.ProductosService.AnswerMessage AddProducto(SPAClientApp.ProductosService.EProducto producto, SPAClientApp.ProductosService.EReceta receta) {
            return base.Channel.AddProducto(producto, receta);
        }
        
        public System.Threading.Tasks.Task<SPAClientApp.ProductosService.AnswerMessage> AddProductoAsync(SPAClientApp.ProductosService.EProducto producto, SPAClientApp.ProductosService.EReceta receta) {
            return base.Channel.AddProductoAsync(producto, receta);
        }
        
        public bool IsDuplicated(string nombreActual, string nombreABuscar) {
            return base.Channel.IsDuplicated(nombreActual, nombreABuscar);
        }
        
        public System.Threading.Tasks.Task<bool> IsDuplicatedAsync(string nombreActual, string nombreABuscar) {
            return base.Channel.IsDuplicatedAsync(nombreActual, nombreABuscar);
        }
        
        public SPAClientApp.ProductosService.AnswerMessage UpdateProducto(SPAClientApp.ProductosService.EProducto producto, SPAClientApp.ProductosService.EReceta receta) {
            return base.Channel.UpdateProducto(producto, receta);
        }
        
        public System.Threading.Tasks.Task<SPAClientApp.ProductosService.AnswerMessage> UpdateProductoAsync(SPAClientApp.ProductosService.EProducto producto, SPAClientApp.ProductosService.EReceta receta) {
            return base.Channel.UpdateProductoAsync(producto, receta);
        }
        
        public SPAClientApp.ProductosService.AnswerMessage ChangeProductoStatus(int productoID, string status) {
            return base.Channel.ChangeProductoStatus(productoID, status);
        }
        
        public System.Threading.Tasks.Task<SPAClientApp.ProductosService.AnswerMessage> ChangeProductoStatusAsync(int productoID, string status) {
            return base.Channel.ChangeProductoStatusAsync(productoID, status);
        }
        
        public string CheckIngredientesStatus(SPAClientApp.ProductosService.EIngrediente[] ingredientes) {
            return base.Channel.CheckIngredientesStatus(ingredientes);
        }
        
        public System.Threading.Tasks.Task<string> CheckIngredientesStatusAsync(SPAClientApp.ProductosService.EIngrediente[] ingredientes) {
            return base.Channel.CheckIngredientesStatusAsync(ingredientes);
        }
    }
}
