//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPAClientApp.ClientesService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ECliente", Namespace="http://schemas.datacontract.org/2004/07/Services.Model")]
    [System.SerializableAttribute()]
    public partial class ECliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoPostalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SPAClientApp.ClientesService.EDireccion[] DireccionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EdadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ciudad {
            get {
                return this.CiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadField, value) != true)) {
                    this.CiudadField = value;
                    this.RaisePropertyChanged("Ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoPostal {
            get {
                return this.CodigoPostalField;
            }
            set {
                if ((this.CodigoPostalField.Equals(value) != true)) {
                    this.CodigoPostalField = value;
                    this.RaisePropertyChanged("CodigoPostal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SPAClientApp.ClientesService.EDireccion[] Direcciones {
            get {
                return this.DireccionesField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionesField, value) != true)) {
                    this.DireccionesField = value;
                    this.RaisePropertyChanged("Direcciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Edad {
            get {
                return this.EdadField;
            }
            set {
                if ((this.EdadField.Equals(value) != true)) {
                    this.EdadField = value;
                    this.RaisePropertyChanged("Edad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Nacimiento {
            get {
                return this.NacimientoField;
            }
            set {
                if ((this.NacimientoField.Equals(value) != true)) {
                    this.NacimientoField = value;
                    this.RaisePropertyChanged("Nacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EDireccion", Namespace="http://schemas.datacontract.org/2004/07/Services.Model")]
    [System.SerializableAttribute()]
    public partial class EDireccion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColoniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Calle {
            get {
                return this.CalleField;
            }
            set {
                if ((object.ReferenceEquals(this.CalleField, value) != true)) {
                    this.CalleField = value;
                    this.RaisePropertyChanged("Calle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Colonia {
            get {
                return this.ColoniaField;
            }
            set {
                if ((object.ReferenceEquals(this.ColoniaField, value) != true)) {
                    this.ColoniaField = value;
                    this.RaisePropertyChanged("Colonia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCliente {
            get {
                return this.IdClienteField;
            }
            set {
                if ((this.IdClienteField.Equals(value) != true)) {
                    this.IdClienteField = value;
                    this.RaisePropertyChanged("IdCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnswerMessage", Namespace="http://schemas.datacontract.org/2004/07/Services.Model")]
    [System.SerializableAttribute()]
    public partial class AnswerMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Key {
            get {
                return this.KeyField;
            }
            set {
                if ((this.KeyField.Equals(value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClientesService.IClientesService")]
    public interface IClientesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientesService/GetCliente", ReplyAction="http://tempuri.org/IClientesService/GetClienteResponse")]
        SPAClientApp.ClientesService.ECliente GetCliente(int IDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientesService/GetCliente", ReplyAction="http://tempuri.org/IClientesService/GetClienteResponse")]
        System.Threading.Tasks.Task<SPAClientApp.ClientesService.ECliente> GetClienteAsync(int IDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientesService/GetClientesList", ReplyAction="http://tempuri.org/IClientesService/GetClientesListResponse")]
        string[] GetClientesList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientesService/GetClientesList", ReplyAction="http://tempuri.org/IClientesService/GetClientesListResponse")]
        System.Threading.Tasks.Task<string[]> GetClientesListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientesService/AddCliente", ReplyAction="http://tempuri.org/IClientesService/AddClienteResponse")]
        SPAClientApp.ClientesService.AnswerMessage AddCliente(SPAClientApp.ClientesService.ECliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientesService/AddCliente", ReplyAction="http://tempuri.org/IClientesService/AddClienteResponse")]
        System.Threading.Tasks.Task<SPAClientApp.ClientesService.AnswerMessage> AddClienteAsync(SPAClientApp.ClientesService.ECliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientesService/UpdateCliente", ReplyAction="http://tempuri.org/IClientesService/UpdateClienteResponse")]
        SPAClientApp.ClientesService.AnswerMessage UpdateCliente(SPAClientApp.ClientesService.ECliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientesService/UpdateCliente", ReplyAction="http://tempuri.org/IClientesService/UpdateClienteResponse")]
        System.Threading.Tasks.Task<SPAClientApp.ClientesService.AnswerMessage> UpdateClienteAsync(SPAClientApp.ClientesService.ECliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientesService/GetClienteByPedido", ReplyAction="http://tempuri.org/IClientesService/GetClienteByPedidoResponse")]
        SPAClientApp.ClientesService.ECliente GetClienteByPedido(int IdPedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientesService/GetClienteByPedido", ReplyAction="http://tempuri.org/IClientesService/GetClienteByPedidoResponse")]
        System.Threading.Tasks.Task<SPAClientApp.ClientesService.ECliente> GetClienteByPedidoAsync(int IdPedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientesService/GetClientes", ReplyAction="http://tempuri.org/IClientesService/GetClientesResponse")]
        SPAClientApp.ClientesService.ECliente[] GetClientes(string status, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientesService/GetClientes", ReplyAction="http://tempuri.org/IClientesService/GetClientesResponse")]
        System.Threading.Tasks.Task<SPAClientApp.ClientesService.ECliente[]> GetClientesAsync(string status, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientesService/ChangeStatusCliente", ReplyAction="http://tempuri.org/IClientesService/ChangeStatusClienteResponse")]
        SPAClientApp.ClientesService.AnswerMessage ChangeStatusCliente(int idCliente, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientesService/ChangeStatusCliente", ReplyAction="http://tempuri.org/IClientesService/ChangeStatusClienteResponse")]
        System.Threading.Tasks.Task<SPAClientApp.ClientesService.AnswerMessage> ChangeStatusClienteAsync(int idCliente, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientesService/UpdateBasicClient", ReplyAction="http://tempuri.org/IClientesService/UpdateBasicClientResponse")]
        SPAClientApp.ClientesService.AnswerMessage UpdateBasicClient(SPAClientApp.ClientesService.ECliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientesService/UpdateBasicClient", ReplyAction="http://tempuri.org/IClientesService/UpdateBasicClientResponse")]
        System.Threading.Tasks.Task<SPAClientApp.ClientesService.AnswerMessage> UpdateBasicClientAsync(SPAClientApp.ClientesService.ECliente cliente);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClientesServiceChannel : SPAClientApp.ClientesService.IClientesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientesServiceClient : System.ServiceModel.ClientBase<SPAClientApp.ClientesService.IClientesService>, SPAClientApp.ClientesService.IClientesService {
        
        public ClientesServiceClient() {
        }
        
        public ClientesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SPAClientApp.ClientesService.ECliente GetCliente(int IDCliente) {
            return base.Channel.GetCliente(IDCliente);
        }
        
        public System.Threading.Tasks.Task<SPAClientApp.ClientesService.ECliente> GetClienteAsync(int IDCliente) {
            return base.Channel.GetClienteAsync(IDCliente);
        }
        
        public string[] GetClientesList() {
            return base.Channel.GetClientesList();
        }
        
        public System.Threading.Tasks.Task<string[]> GetClientesListAsync() {
            return base.Channel.GetClientesListAsync();
        }
        
        public SPAClientApp.ClientesService.AnswerMessage AddCliente(SPAClientApp.ClientesService.ECliente cliente) {
            return base.Channel.AddCliente(cliente);
        }
        
        public System.Threading.Tasks.Task<SPAClientApp.ClientesService.AnswerMessage> AddClienteAsync(SPAClientApp.ClientesService.ECliente cliente) {
            return base.Channel.AddClienteAsync(cliente);
        }
        
        public SPAClientApp.ClientesService.AnswerMessage UpdateCliente(SPAClientApp.ClientesService.ECliente cliente) {
            return base.Channel.UpdateCliente(cliente);
        }
        
        public System.Threading.Tasks.Task<SPAClientApp.ClientesService.AnswerMessage> UpdateClienteAsync(SPAClientApp.ClientesService.ECliente cliente) {
            return base.Channel.UpdateClienteAsync(cliente);
        }
        
        public SPAClientApp.ClientesService.ECliente GetClienteByPedido(int IdPedido) {
            return base.Channel.GetClienteByPedido(IdPedido);
        }
        
        public System.Threading.Tasks.Task<SPAClientApp.ClientesService.ECliente> GetClienteByPedidoAsync(int IdPedido) {
            return base.Channel.GetClienteByPedidoAsync(IdPedido);
        }
        
        public SPAClientApp.ClientesService.ECliente[] GetClientes(string status, string nombre) {
            return base.Channel.GetClientes(status, nombre);
        }
        
        public System.Threading.Tasks.Task<SPAClientApp.ClientesService.ECliente[]> GetClientesAsync(string status, string nombre) {
            return base.Channel.GetClientesAsync(status, nombre);
        }
        
        public SPAClientApp.ClientesService.AnswerMessage ChangeStatusCliente(int idCliente, string status) {
            return base.Channel.ChangeStatusCliente(idCliente, status);
        }
        
        public System.Threading.Tasks.Task<SPAClientApp.ClientesService.AnswerMessage> ChangeStatusClienteAsync(int idCliente, string status) {
            return base.Channel.ChangeStatusClienteAsync(idCliente, status);
        }
        
        public SPAClientApp.ClientesService.AnswerMessage UpdateBasicClient(SPAClientApp.ClientesService.ECliente cliente) {
            return base.Channel.UpdateBasicClient(cliente);
        }
        
        public System.Threading.Tasks.Task<SPAClientApp.ClientesService.AnswerMessage> UpdateBasicClientAsync(SPAClientApp.ClientesService.ECliente cliente) {
            return base.Channel.UpdateBasicClientAsync(cliente);
        }
    }
}
