//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPAClientApp.PedidosClientesService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EPedidoCliente", Namespace="http://schemas.datacontract.org/2004/07/Services.Model")]
    [System.SerializableAttribute()]
    public partial class EPedidoCliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CostoTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EntregaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NumeroProductosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoPedidoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double CostoTotal {
            get {
                return this.CostoTotalField;
            }
            set {
                if ((this.CostoTotalField.Equals(value) != true)) {
                    this.CostoTotalField = value;
                    this.RaisePropertyChanged("CostoTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Entrega {
            get {
                return this.EntregaField;
            }
            set {
                if ((this.EntregaField.Equals(value) != true)) {
                    this.EntregaField = value;
                    this.RaisePropertyChanged("Entrega");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumeroProductos {
            get {
                return this.NumeroProductosField;
            }
            set {
                if ((this.NumeroProductosField.Equals(value) != true)) {
                    this.NumeroProductosField = value;
                    this.RaisePropertyChanged("NumeroProductos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Solicitud {
            get {
                return this.SolicitudField;
            }
            set {
                if ((this.SolicitudField.Equals(value) != true)) {
                    this.SolicitudField = value;
                    this.RaisePropertyChanged("Solicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoPedido {
            get {
                return this.TipoPedidoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoPedidoField, value) != true)) {
                    this.TipoPedidoField = value;
                    this.RaisePropertyChanged("TipoPedido");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EProductoComprado", Namespace="http://schemas.datacontract.org/2004/07/Services.Model")]
    [System.SerializableAttribute()]
    public partial class EProductoComprado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoPedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoProductoVentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CodigoRecetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecioCompraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecioVentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RestriccionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int stockField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoPedido {
            get {
                return this.CodigoPedidoField;
            }
            set {
                if ((this.CodigoPedidoField.Equals(value) != true)) {
                    this.CodigoPedidoField = value;
                    this.RaisePropertyChanged("CodigoPedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoProductoVenta {
            get {
                return this.CodigoProductoVentaField;
            }
            set {
                if ((this.CodigoProductoVentaField.Equals(value) != true)) {
                    this.CodigoProductoVentaField = value;
                    this.RaisePropertyChanged("CodigoProductoVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CodigoReceta {
            get {
                return this.CodigoRecetaField;
            }
            set {
                if ((this.CodigoRecetaField.Equals(value) != true)) {
                    this.CodigoRecetaField = value;
                    this.RaisePropertyChanged("CodigoReceta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PrecioCompra {
            get {
                return this.PrecioCompraField;
            }
            set {
                if ((this.PrecioCompraField.Equals(value) != true)) {
                    this.PrecioCompraField = value;
                    this.RaisePropertyChanged("PrecioCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PrecioVenta {
            get {
                return this.PrecioVentaField;
            }
            set {
                if ((this.PrecioVentaField.Equals(value) != true)) {
                    this.PrecioVentaField = value;
                    this.RaisePropertyChanged("PrecioVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Restricciones {
            get {
                return this.RestriccionesField;
            }
            set {
                if ((object.ReferenceEquals(this.RestriccionesField, value) != true)) {
                    this.RestriccionesField = value;
                    this.RaisePropertyChanged("Restricciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int stock {
            get {
                return this.stockField;
            }
            set {
                if ((this.stockField.Equals(value) != true)) {
                    this.stockField = value;
                    this.RaisePropertyChanged("stock");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EProducto", Namespace="http://schemas.datacontract.org/2004/07/Services.Model")]
    [System.SerializableAttribute()]
    public partial class EProducto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CodigoRecetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecioCompraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecioVentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RestriccionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CodigoReceta {
            get {
                return this.CodigoRecetaField;
            }
            set {
                if ((this.CodigoRecetaField.Equals(value) != true)) {
                    this.CodigoRecetaField = value;
                    this.RaisePropertyChanged("CodigoReceta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PrecioCompra {
            get {
                return this.PrecioCompraField;
            }
            set {
                if ((this.PrecioCompraField.Equals(value) != true)) {
                    this.PrecioCompraField = value;
                    this.RaisePropertyChanged("PrecioCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PrecioVenta {
            get {
                return this.PrecioVentaField;
            }
            set {
                if ((this.PrecioVentaField.Equals(value) != true)) {
                    this.PrecioVentaField = value;
                    this.RaisePropertyChanged("PrecioVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Registro {
            get {
                return this.RegistroField;
            }
            set {
                if ((this.RegistroField.Equals(value) != true)) {
                    this.RegistroField = value;
                    this.RaisePropertyChanged("Registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Restricciones {
            get {
                return this.RestriccionesField;
            }
            set {
                if ((object.ReferenceEquals(this.RestriccionesField, value) != true)) {
                    this.RestriccionesField = value;
                    this.RaisePropertyChanged("Restricciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnswerMessage", Namespace="http://schemas.datacontract.org/2004/07/Services.Model")]
    [System.SerializableAttribute()]
    public partial class AnswerMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Key {
            get {
                return this.KeyField;
            }
            set {
                if ((this.KeyField.Equals(value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PedidosClientesService.IPedidosClientesService")]
    public interface IPedidosClientesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidosClientesService/GetPedidosClientesList", ReplyAction="http://tempuri.org/IPedidosClientesService/GetPedidosClientesListResponse")]
        SPAClientApp.PedidosClientesService.EPedidoCliente[] GetPedidosClientesList(string criterio, System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidosClientesService/GetPedidosClientesList", ReplyAction="http://tempuri.org/IPedidosClientesService/GetPedidosClientesListResponse")]
        System.Threading.Tasks.Task<SPAClientApp.PedidosClientesService.EPedidoCliente[]> GetPedidosClientesListAsync(string criterio, System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidosClientesService/GetCommonPedidosList", ReplyAction="http://tempuri.org/IPedidosClientesService/GetCommonPedidosListResponse")]
        SPAClientApp.PedidosClientesService.EPedidoCliente[] GetCommonPedidosList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidosClientesService/GetCommonPedidosList", ReplyAction="http://tempuri.org/IPedidosClientesService/GetCommonPedidosListResponse")]
        System.Threading.Tasks.Task<SPAClientApp.PedidosClientesService.EPedidoCliente[]> GetCommonPedidosListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidosClientesService/GetProductosComprados", ReplyAction="http://tempuri.org/IPedidosClientesService/GetProductosCompradosResponse")]
        SPAClientApp.PedidosClientesService.EProductoComprado[] GetProductosComprados(int clavePedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidosClientesService/GetProductosComprados", ReplyAction="http://tempuri.org/IPedidosClientesService/GetProductosCompradosResponse")]
        System.Threading.Tasks.Task<SPAClientApp.PedidosClientesService.EProductoComprado[]> GetProductosCompradosAsync(int clavePedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidosClientesService/GetProductosList", ReplyAction="http://tempuri.org/IPedidosClientesService/GetProductosListResponse")]
        SPAClientApp.PedidosClientesService.EProducto[] GetProductosList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidosClientesService/GetProductosList", ReplyAction="http://tempuri.org/IPedidosClientesService/GetProductosListResponse")]
        System.Threading.Tasks.Task<SPAClientApp.PedidosClientesService.EProducto[]> GetProductosListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidosClientesService/AddPedidoCliente", ReplyAction="http://tempuri.org/IPedidosClientesService/AddPedidoClienteResponse")]
        SPAClientApp.PedidosClientesService.AnswerMessage AddPedidoCliente(SPAClientApp.PedidosClientesService.EPedidoCliente pedido, SPAClientApp.PedidosClientesService.EProductoComprado[] productos, int idCliente, int idDireccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidosClientesService/AddPedidoCliente", ReplyAction="http://tempuri.org/IPedidosClientesService/AddPedidoClienteResponse")]
        System.Threading.Tasks.Task<SPAClientApp.PedidosClientesService.AnswerMessage> AddPedidoClienteAsync(SPAClientApp.PedidosClientesService.EPedidoCliente pedido, SPAClientApp.PedidosClientesService.EProductoComprado[] productos, int idCliente, int idDireccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidosClientesService/CheckProductosSeleccionados", ReplyAction="http://tempuri.org/IPedidosClientesService/CheckProductosSeleccionadosResponse")]
        string CheckProductosSeleccionados(SPAClientApp.PedidosClientesService.EProductoComprado[] productos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidosClientesService/CheckProductosSeleccionados", ReplyAction="http://tempuri.org/IPedidosClientesService/CheckProductosSeleccionadosResponse")]
        System.Threading.Tasks.Task<string> CheckProductosSeleccionadosAsync(SPAClientApp.PedidosClientesService.EProductoComprado[] productos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidosClientesService/ChangeStatusPedidoCliente", ReplyAction="http://tempuri.org/IPedidosClientesService/ChangeStatusPedidoClienteResponse")]
        SPAClientApp.PedidosClientesService.AnswerMessage ChangeStatusPedidoCliente(int IdPedido, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidosClientesService/ChangeStatusPedidoCliente", ReplyAction="http://tempuri.org/IPedidosClientesService/ChangeStatusPedidoClienteResponse")]
        System.Threading.Tasks.Task<SPAClientApp.PedidosClientesService.AnswerMessage> ChangeStatusPedidoClienteAsync(int IdPedido, string status);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPedidosClientesServiceChannel : SPAClientApp.PedidosClientesService.IPedidosClientesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PedidosClientesServiceClient : System.ServiceModel.ClientBase<SPAClientApp.PedidosClientesService.IPedidosClientesService>, SPAClientApp.PedidosClientesService.IPedidosClientesService {
        
        public PedidosClientesServiceClient() {
        }
        
        public PedidosClientesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PedidosClientesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidosClientesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidosClientesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SPAClientApp.PedidosClientesService.EPedidoCliente[] GetPedidosClientesList(string criterio, System.DateTime fecha) {
            return base.Channel.GetPedidosClientesList(criterio, fecha);
        }
        
        public System.Threading.Tasks.Task<SPAClientApp.PedidosClientesService.EPedidoCliente[]> GetPedidosClientesListAsync(string criterio, System.DateTime fecha) {
            return base.Channel.GetPedidosClientesListAsync(criterio, fecha);
        }
        
        public SPAClientApp.PedidosClientesService.EPedidoCliente[] GetCommonPedidosList() {
            return base.Channel.GetCommonPedidosList();
        }
        
        public System.Threading.Tasks.Task<SPAClientApp.PedidosClientesService.EPedidoCliente[]> GetCommonPedidosListAsync() {
            return base.Channel.GetCommonPedidosListAsync();
        }
        
        public SPAClientApp.PedidosClientesService.EProductoComprado[] GetProductosComprados(int clavePedido) {
            return base.Channel.GetProductosComprados(clavePedido);
        }
        
        public System.Threading.Tasks.Task<SPAClientApp.PedidosClientesService.EProductoComprado[]> GetProductosCompradosAsync(int clavePedido) {
            return base.Channel.GetProductosCompradosAsync(clavePedido);
        }
        
        public SPAClientApp.PedidosClientesService.EProducto[] GetProductosList() {
            return base.Channel.GetProductosList();
        }
        
        public System.Threading.Tasks.Task<SPAClientApp.PedidosClientesService.EProducto[]> GetProductosListAsync() {
            return base.Channel.GetProductosListAsync();
        }
        
        public SPAClientApp.PedidosClientesService.AnswerMessage AddPedidoCliente(SPAClientApp.PedidosClientesService.EPedidoCliente pedido, SPAClientApp.PedidosClientesService.EProductoComprado[] productos, int idCliente, int idDireccion) {
            return base.Channel.AddPedidoCliente(pedido, productos, idCliente, idDireccion);
        }
        
        public System.Threading.Tasks.Task<SPAClientApp.PedidosClientesService.AnswerMessage> AddPedidoClienteAsync(SPAClientApp.PedidosClientesService.EPedidoCliente pedido, SPAClientApp.PedidosClientesService.EProductoComprado[] productos, int idCliente, int idDireccion) {
            return base.Channel.AddPedidoClienteAsync(pedido, productos, idCliente, idDireccion);
        }
        
        public string CheckProductosSeleccionados(SPAClientApp.PedidosClientesService.EProductoComprado[] productos) {
            return base.Channel.CheckProductosSeleccionados(productos);
        }
        
        public System.Threading.Tasks.Task<string> CheckProductosSeleccionadosAsync(SPAClientApp.PedidosClientesService.EProductoComprado[] productos) {
            return base.Channel.CheckProductosSeleccionadosAsync(productos);
        }
        
        public SPAClientApp.PedidosClientesService.AnswerMessage ChangeStatusPedidoCliente(int IdPedido, string status) {
            return base.Channel.ChangeStatusPedidoCliente(IdPedido, status);
        }
        
        public System.Threading.Tasks.Task<SPAClientApp.PedidosClientesService.AnswerMessage> ChangeStatusPedidoClienteAsync(int IdPedido, string status) {
            return base.Channel.ChangeStatusPedidoClienteAsync(IdPedido, status);
        }
    }
}
